import { createSlice } from "@reduxjs/toolkit";

const initialState = [
  {
    id: "1",
    owner_id: "owner_1",
    avatar_url: "path/to/avatar1.png",
    recipe_name: "Recipe 1",
    status: "completed",
    to: "recipient_1",
    date: "2023-04-25",
    category_id: "category_1",
    image_url: "path/to/image1.png",
    amount: 125000000,
    title: "Lương tháng 04/2024",
    date: "Hôm qua",
    amountString: "+ 125,000,000 đ",
    amountStyle: "text-green-500",
    logo: require("../../../assets/icons/ocb.png"),
  },
  {
    id: "2",
    owner_id: "owner_2",
    avatar_url: "path/to/avatar2.png",
    recipe_name: "Recipe 2",
    status: "pending",
    to: "recipient_2",
    date: "2023-04-24",
    category_id: "category_2",
    image_url: "path/to/image2.png",
    amount: -125000000,
    title: "Lương tháng 05/2024",
    date: "Hôm qua",
    amountString: "- 125,000,000 đ",
    amountStyle: "text-red-500",
    logo: require("../../../assets/icons/ocb.png"),
  },

  {
    id: "3",
    owner_id: "owner_2",
    avatar_url: "path/to/avatar2.png",
    recipe_name: "Recipe 2",
    status: "pending",
    to: "recipient_2",
    date: "2023-04-24",
    category_id: "category_2",
    image_url: "path/to/image2.png",
    amount: -125000000,
    title: "Lương tháng 05/2024",
    date: "Hôm qua",
    amountString: "- 125,000,000 đ",
    amountStyle: "text-red-500",
    logo: require("../../../assets/icons/ocb.png"),
  },
  {
    id: "4",
    owner_id: "owner_2",
    avatar_url: "path/to/avatar2.png",
    recipe_name: "Recipe 2",
    status: "pending",
    to: "recipient_2",
    date: "2023-04-24",
    category_id: "category_2",
    image_url: "path/to/image2.png",
    amount: -125000000,
    title: "Lương tháng 05/2024",
    date: "Hợm qua",
    amountString: "- 125,000,000 đ",
    amountStyle: "text-red-500",
    logo: require("../../../assets/icons/ocb.png"),
  },
  {
    id: "5",
    owner_id: "owner_2",
    avatar_url: "path/to/avatar2.png",
    recipe_name: "Recipe 2",
    status: "pending",
    to: "recipient_2",
    date: "2023-04-24",
    category_id: "category_2",
    image_url: "path/to/image2.png",
    amount: -125000000,
    title: "Lương tháng 05/2024",
    date: "Hợm qua",
    amountString: "- 125,000,000 đ",
    amountStyle: "text-red-500",
    logo: require("../../../assets/icons/ocb.png"),
  },
  {
    id: "6",
    owner_id: "owner_2",
    avatar_url: "path/to/avatar2.png",
    recipe_name: "Recipe 2",
    status: "pending",
    to: "recipient_2",
    date: "2023-04-24",
    category_id: "category_2",
    image_url: "path/to/image2.png",
    amount: -125000000,
    title: "Lương tháng 05/2024",
    date: "Hợm qua",
    amountString: "- 125,000,000 đ",
    amountStyle: "text-red-500",
    logo: require("../../../assets/icons/ocb.png"),
  },
  {
    id: "7",
    owner_id: "owner_2",
    avatar_url: "path/to/avatar2.png",
    recipe_name: "Recipe 2",
    status: "pending",
    to: "recipient_2",
    date: "2023-04-24",
    category_id: "category_2",
    image_url: "path/to/image2.png",
    amount: -125000000,
    title: "Lương tháng 05/2024",
    date: "Hợm qua",
    amountString: "- 125,000,000 đ",
    amountStyle: "text-red-500",
    logo: require("../../../assets/icons/ocb.png"),
  },
  {
    id: "8",
    owner_id: "owner_2",
    avatar_url: "path/to/avatar2.png",
    recipe_name: "Recipe 2",
    status: "pending",
    to: "recipient_2",
    date: "2023-04-24",
    category_id: "category_2",
    image_url: "path/to/image2.png",
    amount: -125000000,
    title: "Lương tháng 05/2024",
    date: "Hợm qua",
    amountString: "- 125,000,000 đ",
    amountStyle: "text-red-500",
    logo: require("../../../assets/icons/ocb.png"),
  },
  {
    id: "9",
    owner_id: "owner_2",
    avatar_url: "path/to/avatar2.png",
    recipe_name: "Recipe 2",
    status: "pending",
    to: "recipient_2",
    date: "2023-04-24",
    category_id: "category_2",
    image_url: "path/to/image2.png",
    amount: -125000000,
    title: "Lương tháng 05/2024",
    date: "Hợm qua",
    amountString: "- 125,000,000 đ",
    amountStyle: "text-red-500",
    logo: require("../../../assets/icons/ocb.png"),
  },
  {
    id: "10",
    owner_id: "owner_2",
    avatar_url: "path/to/avatar2.png",
    recipe_name: "Recipe 2",
    status: "pending",
    to: "recipient_2",
    date: "2023-04-24",
    category_id: "category_2",
    image_url: "path/to/image2.png",
    amount: -125000000,
    title: "Lương tháng 05/2024",
    date: "Hợm qua",
    amountString: "- 125,000,000 đ",
    amountStyle: "text-red-500",
    logo: require("../../../assets/icons/ocb.png"),
  },
  {
    id: "11",
    owner_id: "owner_2",
    avatar_url: "path/to/avatar2.png",
    recipe_name: "Recipe 2",
    status: "pending",
    to: "recipient_2",
    date: "2023-04-24",
    category_id: "category_2",
    image_url: "path/to/image2.png",
    amount: -125000000,
    title: "Lương tháng 05/2024",
    date: "Hợm qua",
    amountString: "- 125,000,000 đ",
    amountStyle: "text-red-500",
    logo: require("../../../assets/icons/ocb.png"),
  },
  {
    id: "12",
    owner_id: "owner_2",
    avatar_url: "path/to/avatar2.png",
    recipe_name: "Recipe 2",
    status: "pending",
    to: "recipient_2",
    date: "2023-04-24",
    category_id: "category_2",
    image_url: "path/to/image2.png",
    amount: -125000000,
    title: "Lương tháng 05/2024",
    date: "Hợm qua",
    amountString: "- 125,000,000 đ",
    amountStyle: "text-red-500",
    logo: require("../../../assets/icons/ocb.png"),
  },
];

const transactionsSlice = createSlice({
  name: "transactions",
  initialState,
  reducers: {
    addTransaction: (state, action) => {
      state.push(action.payload);
    },
  },
});

export const { addTransaction } = transactionsSlice.actions;
export default transactionsSlice.reducer;
